<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Develop_Debug</Configurations>
  </PropertyGroup>

  
	
	<Choose>
		<When Condition="'$(Configuration)' == 'Develop_Debug'">
		<ItemGroup>
				<ProjectReference Include="..\..\HttpWebAPICore\HttpWebAPICore\HttpWebAPICore.csproj" />
				<ProjectReference Include="..\..\CoreNavigation\RoutePlanning\RoutePlanning.csproj" />
			</ItemGroup>
		</When>
		<Otherwise>
			<ItemGroup>
				<PackageReference Include="HttpWebAPICore" Version="0.0.3-beta" />
				<PackageReference Include="RoutePlanning" Version="0.0.1-alpha" />
			</ItemGroup>
		</Otherwise>
	</Choose>

  
	
	<ItemGroup>
	  <PackageReference Include="CoordinateSharp" Version="3.1.1.1" />
	  <PackageReference Include="GoogleApi" Version="5.8.4" />
	  <PackageReference Include="NetTopologySuite" Version="2.6.0" />
	  <PackageReference Include="UnitsNet" Version="5.74.0" />
	</ItemGroup>

  
	
	
	


</Project>