# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

env:
  NuGetDirectory: ${{ github.workspace}}/nuget

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        source-url: https://nuget.pkg.github.com/oliverhunt19/index.json
        dotnet-version: 8.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.API_KEY}}  # Note, create a secret with this name in Settings
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal 
      
      
